### ISSUE TITLE
HttpClient and request buffering

### ISSUE THREAD

**Issue by n-think** [DubZero/AspNetCore.Yandex.ObjectStorage#13]
two questions:

1. Why are you not using static HttpClient or some kind of factory to reuse them?
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-5.0#remarks

2. Why is there request buffering,
for example in _GetAsStreamAsync_
we have
```
HttpResponseMessage httpResponseMessage = await client.SendAsync(request);
stream = await httpResponseMessage.Content.ReadAsStreamAsync();
...
return stream;
```
and not 
`HttpResponseMessage httpResponseMessage = await client.SendAsync(request , HttpCompletionOption.ResponseHeadersRead);`
it doubles latency if im returning stream from api

Is there any reasoning for those two? im using this lib and can make pr to fix thisthat

**Comment by DubZero** [comment]
1. Yes, I recently saw several articles on this topic. I will try to use static HttpClient
2. I correctly understood that we need a method to simply return HttpResponseMessage?
3. I will try to fix these issues, and call you to look at PR to make sure that I did the right thing. But if you have more ideas to make it better, you can create PRs.

**Comment by n-think** [comment]
> 1. Yes, I recently saw several articles on this topic. I will try to use static HttpClient
> 2. I correctly understood that we need a method to simply return HttpResponseMessage?
> 3. I will try to fix these issues, and call you to look at PR to make sure that I did the right thing. But if you have more ideas to make it better, you can create PRs.

for 2: i think adding HttpCompletionOption.ResponseHeadersRead to await client.SendAsync will be enough, return stream same as it is

**Comment by DubZero** [comment]
Ok

**Comment by DubZero** [comment]
@n-think do you have access to review [PR](https://github.com/DubZero/AspNetCore.Yandex.ObjectStorage/pull/14)?

**Comment by DubZero** [comment]
I migrate project on Github actions and change the flow. Now deploy works on develop and master dependent branches. So now you can try this on your project using an alpha version from 1.7.3-alpha.

**Comment by n-think** [comment]
> @n-think do you have access to review [PR](https://github.com/DubZero/AspNetCore.Yandex.ObjectStorage/pull/14)?

looks good for me

/upd missed couple places, left comments
