### ISSUE TITLE
Read configuration from appsettings.json

### ISSUE THREAD

**Issue by framebassman** [DubZero/AspNetCore.Yandex.ObjectStorage#3]
As Developer, I want to setup YandexObjectStorage service in `appsettings.json` file, like Serilog (https://github.com/serilog/serilog-settings-configuration)

**Comment by DubZero** [comment]
Hi,
I create pull request #4. Did you mean so?

**Comment by DubZero** [comment]
> Hi,
> I create pull request #4. Did you mean so?
